### ISSUE TITLE
fix leak

### ISSUE THREAD

**Issue by greenaddress** [greenaddress/GreenBits#56]
`04-03 23:42:52.459 20296-20296/com.greenaddress.greenbits_android_wallet E/WindowManager: android.view.WindowLeaked: Activity com.greenaddress.greenbits.ui.TabbedMainActivity has leaked window android.widget.PopupWindow$PopupDecorView{c8adcb7 V.E...... ........ 0,0-515,504} that was originally added here
                                                                                              at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
                                                                                              at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
                                                                                              at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                                                                                              at android.widget.PopupWindow.invokePopup(PopupWindow.java:1258)
                                                                                              at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1110)
                                                                                              at android.support.v7.widget.AppCompatPopupWindow.showAsDropDown(AppCompatPopupWindow.java:78)
                                                                                              at android.support.v4.widget.PopupWindowCompatKitKat.showAsDropDown(PopupWindowCompatKitKat.java:30)
                                                                                              at android.support.v4.widget.PopupWindowCompat$KitKatPopupWindowImpl.showAsDropDown(PopupWindowCompat.java:92)
                                                                                              at android.support.v4.widget.PopupWindowCompat.showAsDropDown(PopupWindowCompat.java:171)
                                                                                              at android.support.v7.widget.ListPopupWindow.show(ListPopupWindow.java:680)
                                                                                              at android.support.v7.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:163)
                                                                                              at android.support.v7.widget.ActionMenuPresenter$OpenOverflowRunnable.run(ActionMenuPresenter.java:781)
                                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by jgriffiths** [comment]
leaks like these are caused by other exceptions at critical points and will be tackled as bugs against the original exceptions. Also it looks like this one is fixed.

**Comment by greenaddress** [comment]
This issue seems still open.

Tested on Android API level 23 (Android 6) on x86-64 AVD

`WindowManager: android.view.WindowLeaked: Activity com.greenaddress.greenbits.ui.TabbedMainActivity has leaked window android.widget.PopupWindow$PopupDecorView{86ff32b V.E...... ........ 0,0-515,630} that was originally added here
                     at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
                     at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
                     at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                     at android.widget.PopupWindow.invokePopup(PopupWindow.java:1258)
                     at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1110)
                     at android.support.v7.widget.AppCompatPopupWindow.showAsDropDown(AppCompatPopupWindow.java:102)
                     at android.support.v4.widget.PopupWindowCompatKitKat.showAsDropDown(PopupWindowCompatKitKat.java:30)
                     at android.support.v4.widget.PopupWindowCompat$KitKatPopupWindowImpl.showAsDropDown(PopupWindowCompat.java:129)
                     at android.support.v4.widget.PopupWindowCompat.showAsDropDown(PopupWindowCompat.java:206)
                     at android.support.v7.widget.ListPopupWindow.show(ListPopupWindow.java:715)
                     at android.support.v7.view.menu.StandardMenuPopup.tryShow(StandardMenuPopup.java:160)
                     at android.support.v7.view.menu.StandardMenuPopup.show(StandardMenuPopup.java:187)
                     at android.support.v7.view.menu.MenuPopupHelper.showPopup(MenuPopupHelper.java:286)
                     at android.support.v7.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:171)
                     at android.support.v7.widget.ActionMenuPresenter$OpenOverflowRunnable.run(ActionMenuPresenter.java:803)
                     at android.os.Handler.handleCallback(Handler.java:739)
                     at android.os.Handler.dispatchMessage(Handler.java:95)
                     at android.os.Looper.loop(Looper.java:148)
                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                     at java.lang.reflect.Method.invoke(Native Method)
                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by jgriffiths** [comment]
This is caused when a dialog is created by an activity or fragment and the activity is then paused. It doesn't occur in the cases where we hold the dialog as a member and dismiss it when the activity is paused, or if it is dismissed beforehand by the user.

Ideally the activity and fragment base classes would have some generic code to register and unregister dialogs, then close them automatically to prevent the reported leak (which otherwise seems harmless).
